# Generated by Django 4.2.9 on 2024-01-13 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=1000)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to=settings.AUTH_USER_MODEL)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=10000)),
                ('sent_date', models.DateTimeField(default=datetime.datetime(2024, 1, 13, 16, 57, 34, 837429))),
                ('image', models.FileField(upload_to='history')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.roomnames')),
            ],
        ),
    ]
