# Generated by Django 4.2.9 on 2024-01-13 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_messagehistory_image_messagehistory_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='sent_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 13, 18, 34, 40, 147216, tzinfo=datetime.timezone.utc)),
        ),
    ]
