# Generated by Django 4.2.9 on 2024-01-13 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_alter_messagehistory_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='sent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
